### PR TITLE
Update example dependencies to use Grafana 9.1.2

### PR DESCRIPTION
**Pull request by academo**
Updates all the existing examples, except datasource-http to use Grafana 9.0.7

### CODE REVIEW

**Comment by tolzhabayev** [comment]
https://github.com/grafana/grafana-plugin-examples/blob/master/examples/panel-basic/src/components/SimplePanel/SimplePanel.tsx#L30 expects `timeZones`?

```
ERROR in ./src/components/SimplePanel/SimplePanel.tsx:30:9
TS2322: Type '{ children: (config: UPlotConfigBuilder, alignedDataFrame: DataFrame) => Element; width: number; height: number; timeRange: TimeRange; timeZone: string; frames: DataFrame[]; legend: VizLegendOptions; }' is not assignable to type 'IntrinsicAttributes & { fields?: XYFieldMatchers | undefined; width: number; options?: Record<string, any> | undefined; children?: ((builder: UPlotConfigBuilder, alignedFrame: DataFrame) => ReactNode) | undefined; ... 10 more ...; preparePlotFrame?: ((frames: DataFrame[], dimFields: XYFieldMatchers) => DataFrame) | ...'.
  Property 'timeZone' does not exist on type 'IntrinsicAttributes & { fields?: XYFieldMatchers | undefined; width: number; options?: Record<string, any> | undefined; children?: ((builder: UPlotConfigBuilder, alignedFrame: DataFrame) => ReactNode) | undefined; ... 10 more ...; preparePlotFrame?: ((frames: DataFrame[], dimFields: XYFieldMatchers) => DataFrame) | ...'. Did you mean 'timeZones'?
    [28](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:29) |         height={height}
    [29](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:30) |         timeRange={timeRange}
  > [30](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:31) |         timeZone={timeZone}
       |         ^^^^^^^^
    [31](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:32) |         frames={data.series}
    [32](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:33) |         legend={options.legend}
    [33](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:34) |       >
```

**Comment by academo** [comment]
> [https://github.com/grafana/grafana-plugin-examples/blob/master/examples/panel-basic/src/components/SimplePanel/SimplePanel.tsx#L30](https://github.com/grafana/grafana-plugin-examples/blob/master/examples/panel-basic/src/components/SimplePanel/SimplePanel.tsx?rgh-link-date=2022-08-31T12%3A54%3A21Z#L30) expects `timeZones`? I though we have patched it?
> 
> ```
> ERROR in ./src/components/SimplePanel/SimplePanel.tsx:30:9
> TS2322: Type '{ children: (config: UPlotConfigBuilder, alignedDataFrame: DataFrame) => Element; width: number; height: number; timeRange: TimeRange; timeZone: string; frames: DataFrame[]; legend: VizLegendOptions; }' is not assignable to type 'IntrinsicAttributes & { fields?: XYFieldMatchers | undefined; width: number; options?: Record<string, any> | undefined; children?: ((builder: UPlotConfigBuilder, alignedFrame: DataFrame) => ReactNode) | undefined; ... 10 more ...; preparePlotFrame?: ((frames: DataFrame[], dimFields: XYFieldMatchers) => DataFrame) | ...'.
>   Property 'timeZone' does not exist on type 'IntrinsicAttributes & { fields?: XYFieldMatchers | undefined; width: number; options?: Record<string, any> | undefined; children?: ((builder: UPlotConfigBuilder, alignedFrame: DataFrame) => ReactNode) | undefined; ... 10 more ...; preparePlotFrame?: ((frames: DataFrame[], dimFields: XYFieldMatchers) => DataFrame) | ...'. Did you mean 'timeZones'?
>     [28](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:29[](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:29)) |         height={height}
>     [29](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:30[](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:30)) |         timeRange={timeRange}
>   > [30](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:31[](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:31)) |         timeZone={timeZone}
>        |         ^^^^^^^^
>     [31](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:32[](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:32)) |         frames={data.series}
>     [32](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:33[](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:33)) |         legend={options.legend}
>     [33](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:34[](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true#step:24:34)) |       >
> ```
> 
> [grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true](https://github.com/grafana/grafana-plugin-examples/runs/7913656710?check_suite_focus=true)

This is an old run of the pipeline.

**Comment by tolzhabayev** [comment]
@academo just a thought - should we maybe target `9.1.2` instead?

**Comment by jackw** [comment]
> @academo just a thought - should we maybe target `9.1.2` instead?

Having just reviewed #80 (which uses 9.1.2) I came back to suggest the same. 👍

**Pull request merged**
