### PR TITLE
docs: Add linkspector github action & fix Readme links in examples/app-basic

### LINKED ISSUE #356: links dont work on app basic readme pages
source links on tree/main/examples/app-basic#guides-in-this-example 404

### PR DESCRIPTION
**Pull request by leslie-alldridge**
- Add github action to automatically inspect links and assist with long term maintenance of URLs in documentation
- Repair links for app-basic to the best of my ability

Note: To see the link inspector workflow (you may wish to keep / not keep it / suggest an alternative workflow) feel free to check out this PR on my fork https://github.com/leslie-alldridge/grafana-plugin-examples/pull/1

Resolves #356

### CODE REVIEW

**Comment by andresmgot** [comment]
Adding @josmperez as a reviewer here since you may have an opinion.

**Review by josmperez — APPROVED** [review]
Looking over only changes to the README, LGTM.

**Review by tolzhabayev — APPROVED** [review]

**Comment by tolzhabayev** [comment]
@leslie-alldridge can you please [sign the CLA](https://github.com/grafana/grafana-plugin-examples/pull/358#issuecomment-2307674575) - then I will be able to get this merged.

**Comment by leslie-alldridge** [comment]
@tolzhabayev thanks! i've signed it now :)

**Pull request merged**
