### PR TITLE
Update plugin-e2e dep in ci

### PR DESCRIPTION
**Pull request by sunker**
Updates the plugin-e2e package so that we always run e2e tests using the latest minor/patch in CI.

### CODE REVIEW

**Review by tolzhabayev — APPROVED** [review]
it works, but probably we should think about solving this in examples themselves additionally.

**Comment by sunker** [comment]
> it works, but probably we should think about solving this in examples themselves additionally.

How could we do that?

**Comment by tolzhabayev** [comment]
> > it works, but probably we should think about solving this in examples themselves additionally.
> 
> How could we do that?

dependabot could probably do that - open PRs with updates to this package.

**Comment by jackw** [comment]
> dependabot could probably do that - open PRs with updates to this package. We can theoretically even auto merge those specific ones.

I think this option gets my vote too. Whilst the changes in this PR work it gives us the idea that our e2e tests pass fine but when we run them locally or a developer copies the example as a starting point they'll fail which might cause confusion.

**Comment by sunker** [comment]
> dependabot could probably do that - open PRs with updates to this package.

Yes this makes sense to me. I'll have a look at this

**Comment by sunker** [comment]
Closing this PR in favour of https://github.com/grafana/grafana-plugin-examples/pull/282. Please take a look when you have time @tolzhabayev @jackw.

**Pull request closed without merging**
