### PR TITLE
Examples: App with scenes

### PR DESCRIPTION
**Pull request by dprokop**
This PR introduces https://github.com/grafana/scenes-app-template to the repo

### CODE REVIEW

**Review by leventebalogh — APPROVED** [review]
Nice one! 🎉

**Review by mckn — COMMENTED** [review]
LGTM! Great work on this 🙌🏻

**Comment by dprokop** [comment]
@mckn - the mighty @leventebalogh is actually on it as we speak :)

**Comment by mckn** [comment]
> @mckn - the mighty @leventebalogh is actually on it as we speak :)

mighty

**Comment by leventebalogh** [comment]
Looks like it is not passing locally, but not in the CI (I don't yet know why). I keep investigating.

**Comment by jackw** [comment]
FYI - checks should be passing now. Reasons for failures in CI were down to:

- The `grafanaDependency` was incorrectly set in plugin.json (we rely on that during ci but not during dev for docker container)
- The canary plugin rebuild wasn't blacklisting `grafana/scenes` causing the `yarn install` to go looking for grafana/scenes@10.1.0-pre<hash> which then failed

**Comment by leventebalogh** [comment]
Amazing work debugging this @jackw 🚀!

**Review by jackw — APPROVED** [review]
LGTM! 🚀 

Awesome work on this @dprokop 🥇

**Pull request merged**
